---
- name: Deploy app from Jenkins GitHub clone to all servers
  hosts: webservers
  become: yes

  tasks:
    - name: Ensure app directory exists
      file:
        path: /home/sajja_vamsi/app
        state: directory
        mode: '0755'

    - name: Copy code from Jenkins workspace
      copy:
        src: "{{ playbook_dir }}/../"
        dest: /home/sajja_vamsi/app/
        mode: '0755'

    - name: Ensure Python3 and venv are installed
      apt:
        name:
          - python3
          - python3-venv
        state: present
        update_cache: yes

    - name: Create Python virtual environment
      command: python3 -m venv /home/sajja_vamsi/app/venv
      args:
        creates: /home/sajja_vamsi/app/venv

    - name: Install Flask in virtual environment
      shell: |
        source /home/sajja_vamsi/app/venv/bin/activate
        pip install flask
      args:
        executable: /bin/bash

    - name: Run the app using venv in background (async)
      shell: |
        pkill -f "python" || true
        source /home/sajja_vamsi/app/venv/bin/activate
        nohup python /home/sajja_vamsi/app/app.py > /home/sajja_vamsi/app/log.txt 2>&1 &
      args:
        executable: /bin/bash
      async: 60
      poll: 0
